"""Deterministic yt-dlp test double for Docker integration tests.

The real YouTube extractor is intentionally bypassed when an integration test sets
``GETOFFLINE_YTDLP_MODULE=workers.fake_ytdlp``. The fake implements the tiny
``YoutubeDL`` surface used by the downloader: context manager support,
``extract_info()``, and ``prepare_filename()``. It writes a small media artifact
and a post-conversion SRT sidecar so the downstream FFmpeg/transcript/profanity
pipeline can run without making any request to YouTube.
"""

from __future__ import annotations

import io
import re
import wave
from pathlib import Path
from string import Template
from typing import Any

_VIDEO_ID = "BB49x_uMlGA"
_TITLE = "Integration YouTube runtime video"
_UPLOADER = "Integration YouTube Runtime"


class YoutubeDL:
    def __init__(self, opts: dict[str, Any] | None = None) -> None:
        self.opts = opts or {}
        self._last_info: dict[str, Any] | None = None

    def __enter__(self) -> "YoutubeDL":
        return self

    def __exit__(self, exc_type, exc, traceback) -> None:  # noqa: ANN001
        return None

    def extract_info(self, url: str, download: bool = True) -> dict[str, Any]:
        info = {
            "id": _VIDEO_ID,
            "title": _TITLE,
            "description": "Synthetic integration-test media generated by fake yt-dlp.",
            "uploader": _UPLOADER,
            "channel": _UPLOADER,
            "webpage_url": url,
            "duration": 2,
            "upload_date": "20260101",
            "extractor": "youtube",
            "extractor_key": "Youtube",
            "ext": "m4a",
        }
        media_path = Path(self.prepare_filename(info)).expanduser().resolve()
        if download:
            media_path.parent.mkdir(parents=True, exist_ok=True)
            media_path.write_bytes(_silent_wav_bytes())
            _write_subtitle_sidecar(media_path.with_suffix(".converted.srt"))
            for hook in self.opts.get("progress_hooks") or []:
                hook(
                    {
                        "status": "finished",
                        "filename": str(media_path),
                        "info_dict": info,
                    }
                )
            info["filepath"] = str(media_path)
            info["requested_downloads"] = [{"filepath": str(media_path)}]
        self._last_info = info
        return info

    def prepare_filename(self, info: dict[str, Any]) -> str:
        outtmpl = str(self.opts.get("outtmpl") or "%(title)s [%(id)s].%(ext)s")
        values = {
            "id": str(info.get("id") or _VIDEO_ID),
            "title": _sanitize_filename(str(info.get("title") or _TITLE)),
            "ext": str(info.get("ext") or "m4a"),
        }
        return _render_outtmpl(outtmpl, values)


def _render_outtmpl(outtmpl: str, values: dict[str, str]) -> str:
    # Support the yt-dlp placeholders used by GetOffline, including width
    # modifiers like %(title).200B. Unknown placeholders are left readable.
    def replace(match: re.Match[str]) -> str:
        key = match.group("key")
        value = values.get(key, key)
        limit = match.group("limit")
        if limit and limit.isdigit():
            value = value[: int(limit)]
        return value

    rendered = re.sub(r"%\((?P<key>[^)]+)\)(?:\.(?P<limit>\d+)B)?s?", replace, outtmpl)
    return Template(rendered).safe_substitute(values)


def _sanitize_filename(value: str) -> str:
    cleaned = re.sub(r"[\\/:*?\"<>|]+", " ", value).strip()
    return re.sub(r"\s+", " ", cleaned) or "download"


def _silent_wav_bytes() -> bytes:
    buffer = io.BytesIO()
    sample_rate = 8000
    duration_seconds = 2
    with wave.open(buffer, "wb") as wav_file:
        wav_file.setnchannels(1)
        wav_file.setsampwidth(2)
        wav_file.setframerate(sample_rate)
        wav_file.writeframes(b"\x00\x00" * sample_rate * duration_seconds)
    return buffer.getvalue()


def _write_subtitle_sidecar(path: Path) -> None:
    path.write_text(
        "1\n"
        "00:00:00,000 --> 00:00:02,000\n"
        "This clean integration transcript was generated offline.\n\n",
        encoding="utf-8",
    )
