config_version: 2
common:
  source_code_url: "__SOURCE_CODE_URL__"
  revision: "__REVISION__"
  framework: "fastapi"
  project_root: "getoffline"
  project_user: "jellyfin"
  venv_dir: ".venv"
  package_manager: "pip"
  dependency_file: "src/requirements.txt"
  keep_releases: 5
  system_packages: |
    python3.12
    python3.12-venv
    ffmpeg
    deno
  ssh_known_hosts: "github.com"
  service_file: "./deploy/getoffline/production/getoffline.service"
  clone_depth: 0
servers:
  - host: "jellyfin@localhost"
    port: 22
    run_migrations: false
    collect_static_files: false
